export const BIKE_MODELS: Record<string, string[]> = {
  Calibre: ['Bossnut', 'Two Cubed', 'Bozeman'],
  Cannondale: ['Jekyll', 'Scalpel', 'Habit', 'Cujo', 'Claymore', 'SuperSixEVO'],
  Cotic: ['BfeMAX', 'Rocket', 'FlareMAX', 'SolarisMAX', 'RapidFire'],
  Cube: ['Stereo', 'Ams', 'Reaction', 'Attention', 'Two15', 'Hanzz'],
  Decathlon: ['ST 900', 'ST 540', 'AM 100', 'XC 500'],
  Devinci: ['Spartan', 'Troy', 'Marshall', 'Holt', 'Kobain'],
  Diamondback: ['Release', 'Catch', 'Sync\'d', 'Mason'],
  Evil: ['Wreckoning', 'Following', 'Offering', 'Undead'],
  Fuji: ['Tahoe', 'Outland', 'Aurum', 'Jari'],
  Giant: ['Trance', 'Reign', 'Anthem', 'Stance', 'Liv Intrigue'],
  GT: ['Fury', 'Sanction', 'Verb', 'Force', 'Avalanche'],
  Haro: ['Shift', 'Aro', 'Capo'],
  Huffy: ['Nighthawk', 'Phantom', 'Hardtail'],
  Ibis: ['Ripmo', 'Ripley', 'Mojo', 'DV9'],
  Intense: ['Tracer', 'Uzzi', 'Carbine', 'VPP'],
  Kona: ['Process', 'Precept', 'Satori', 'Honzo', 'Operator'],
  Marin: ['Hawk Hill', 'Alpine Trail', 'Rift Zone', 'Team Issue', 'Eldridge Grade'],
  Merida: ['One-Sixty', 'eOne-Sixty', 'Big.Nine', 'Ninety-Six'],
  Mongoose: ['Salvo', 'XR-200', 'Legion', 'Status'],
  Niner: ['RIP 9', 'RIP 9 RDO', 'JET 9', 'ONE'],
  Norco: ['Sight', 'Range', 'Optic', 'Revolver'],
  Nukeproof: ['Mega', 'Reactor', 'Giga', 'Scout'],
  Orange: ['Five', 'Patriot', 'Two', 'Alpine'],
  Pivot: ['Shadowcat', 'Phoenix', 'Mach 5', 'Firebird', 'Trail 429'],
  Polygon: ['Siskiu', 'D-Line', 'Premier', 'DMA'],
  Propain: ['Tyee', 'Hugene', 'Spindrift', 'Hantelmann', 'Parametron'],
  Ragley: ['Big Al', 'Marauder', 'Piglet'],
  'Rocky Mountain': ['Altitude', 'Instinct', 'Element', 'Pipeline'],
  'Salsa Cycles': ['Beargrease', 'Deadwood', 'Timberjack', 'Horseshoe'],
  'Santa Cruz': ['Hightower', 'Megatower', 'Bronson', 'Blur', 'Tallboy'],
  Scott: ['Genius', 'Ransom', 'Slash', 'Voltage'],
  Specialized: ['Stumpjumper', 'Enduro', 'Demo', 'Status', 'Slayer'],
  Surly: ['Karate Monkey', 'Krampus', 'Wednesday', 'Lowside'],
  Trek: ['Slash', 'Fuel EX', 'Remedy', 'Sensor', 'Supercaliber'],
  Transition: ['Sentinel', 'Smuggler', 'Patrol', 'Spur'],
  Vitus: ['Sommet', 'Nucleon', 'Mythique', 'Raptor'],
  Whyte: ['E-150', 'E-160', 'E-170', 'G-160', 'T-130S'],
  Yeti: ['SB165', 'SB140', 'SB150', 'Arc'],
};
